document.write("<header class=\"header\" >");
document.write("       <div class=\"container\">");
document.write("           <div class=\"row\">");
document.write("               <div class=\"col-md-12\">");
document.write("                   <nav class=\"navbar navbar-expand-lg navbar_header\">");
document.write("                       <a class=\"navbar-brand logo\" href=\"index.html\">");
document.write("                           <img src=\"assets/images/logo.png\" alt=\"logo\">");
document.write("                       </a>");
document.write("                       <button class=\"navbar-toggler navbar_btn\" type=\"button\" data-toggle=\"collapse\" data-target=\"#headerNavbar\" aria-expanded=\"false\">");
document.write("                           <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 30 30\" width=\"30\" height=\"30\" focusable=\"false\"><path stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" d=\"M4 7h22M4 15h22M4 23h22\"></path></svg>");
document.write("                       </button>");
document.write("                        <div class=\"collapse navbar-collapse header_menu\" id=\"headerNavbar\">");
document.write("                           <ul class=\"navbar-nav ml-auto\">");
document.write("                               <li class=\"nav-item\">");
document.write("                                   <a class=\"nav-link\" href=\"index.html\">Home</a>");
document.write("                               </li>                                ");
document.write("                               <li class=\"nav-item\">");
document.write("                                   <a class=\"nav-link\" href=\"index.html#solution\">Solution</a>");
document.write("                               </li> ");
document.write("                               <li class=\"nav-item\">");
document.write("                                   <a class=\"nav-link\" href=\"https://dashboard.catchup.cloud/accounts/signup/\">Signup</a>");
document.write("                               </li>");
document.write("                           </ul>                           ");
document.write("                       </div>");
document.write("                   </nav>");
document.write("               </div>");
document.write("           </div>");
document.write("       </div>");
document.write("   </header>");